# Generated by Django 5.2.8 on 2026-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('PROJECT_CREATED', 'Project created'), ('PROJECT_UPDATED', 'Project updated'), ('PROJECT_DELETED', 'Project deleted'), ('TASK_CREATED', 'Task created'), ('TASK_UPDATED', 'Task updated'), ('TASK_DELETED', 'Task deleted'), ('TASK_COMMENTED', 'Task comment added'), ('TASK_ASSIGNED', 'Task assigned'), ('TASK_STATUS_CHANGED', 'Task status changed'), ('MEMBER_ADDED', 'Member added'), ('MEMBER_REMOVED', 'Member removed'), ('SYSTEM_EVENT', 'System event')], max_length=64)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
