# Generated by Django 5.2.8 on 2026-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task assigned'), ('COMMENT_ADDED', 'Comment added'), ('DEADLINE_NEAR', 'Project deadline near')], default='TASK_ASSIGNED', max_length=64)),
            ],
        ),
    ]
